### ISSUE TITLE
unable to add current logged in user to group

### ISSUE THREAD

**Issue by ayoakpata** [thomast1906/DevOps-Journey-Using-Azure-DevOps#26]
running the script to auto create group and add currently logged in user only creates the group...trying to add user throws error

←[91margument --member-id: expected one argument←[0m

Examples from AI knowledge base:
←[94maz←[94m ad←[94m group←[94m member←[94m add←[94m --group←[0m MyGroupDisplayName←[94m --member-id←[0m xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx←[0m
←[90mAdd a member to a group. (autogenerated)
←[0m
←[96mhttps://docs.microsoft.com/en-US/cli/azure/ad/group/member#az_ad_group_member_add←[0m
←[90mRead more about the command in reference docs←[0m
AZURE AD GROUP ID IS:

**Comment by thomast1906** [comment]
Can you include full error output?

**Comment by orbsfoc** [comment]
CURRENT_USER_OBJECTID=$(az ad signed-in-user show --query objectId -o tsv)

should be:
CURRENT_USER_OBJECTID=$(az ad signed-in-user show --query id -o tsv)

in create-azure-ad-group.sh by the looks of it

**Comment by A-Larsen** [comment]
Same issue here. I agree with the above suggestion

**Comment by thomast1906** [comment]
Thank you all - now fixed it in https://github.com/thomast1906/DevOps-Journey-Using-Azure-DevOps/pull/37 

Apologies for the delay.
